// src/components/react/Header.tsx
import React, { FormEventHandler, useEffect, useState } from "react";
import { trackEvent } from "@/utils/window";
import { SaveAndGoBackButton } from "./SaveAndGoBackButton";
import yaml from "js-yaml";

interface Props {
  saveAndExit: VoidFunction;
}
const Component = ({ saveAndExit }: Props) => {
  const [title, setTitle] = useState("");

  const helpClick = () => {
    trackEvent("help", "click", "open-api");
  };
  const changeTitle: FormEventHandler<HTMLInputElement> = e => {
    setTitle(e.currentTarget.value);
    if (window.diagram) {
      window.diagram.title = e.currentTarget.value;
      yaml.loadAll(window.specContent || '', function (data) {
        const doc: Record<string, any> = data as any;
        doc.info.title = e.currentTarget.value;
        window.editor.specActions.updateSpec(yaml.dump(doc));
      });
    }
  };
  useEffect(() => {
    if (window.diagram) {
      yaml.loadAll(window.diagram.code || '', function (data) {
        const doc: Record<string, any> = data as any;
        if (doc?.info?.title) setTitle(doc.info.title);
      });
    }
    const handleEditorChange = (spec: string) => {
      yaml.loadAll(spec, function (data) {
        const doc: Record<string, any> = data as any;
        setTitle(doc?.info?.title || '');
      });
    };
    if (!window.specListeners) window.specListeners = [];
    window.specListeners.push(handleEditorChange);
    return () => {
      if (!window.specListeners) return
      window.specListeners = window.specListeners.filter(
        (listener: any) => listener !== handleEditorChange
      );
    };
  }, []);

  return (
    <header className="toolbar header border-b border-gray-800 p-2 flex items-center justify-between w-full">
      <div className="flex">
        <input
          className="px-1 border-2 border-solid border-[#091e4224] rounded-[3px] focus:border-[#388bff] hover:border-[#388bff] outline-none transition-[border-color] leading-7"
          type="text"
          placeholder="Title"
          value={title}
          onInput={changeTitle}
        />
      </div>
      <div className="flex items-center">
        <a
          className="inline-block help mx-1 ml-2"
          target="_blank"
          href="helpUrl"
        >
          <button
            className="flex items-center bg-gray-100 px-2 py-1 text-gray-600 text-sm font-semibold rounded"
            onClick={helpClick}
          >
            <span>
              <svg
                className="w-4 h-4"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                ></path>
              </svg>
            </span>
            <span>Help</span>
          </button>
        </a>
        <div className="inline-block ml-2">
          <SaveAndGoBackButton saveAndExit={saveAndExit} />
        </div>
      </div>
    </header>
  );
};

export default Component;

// src/components/Header.vue
<template>
  <header class="toolbar header border-b border-gray-800 p-2 flex items-center justify-between">
    <div class="inline-block group ml-2 p-0.5 rounded-lg flex bg-gray-100 hover:bg-gray-200">
      <button type="button"
              class="flex focus-visible:ring-2 focus-visible:ring-teal-500 focus-visible:ring-offset-2 rounded-md focus:outline-none focus-visible:ring-offset-gray-100"
              :class="diagramType === 'sequence' ? 'bg-white shadow-sm ring-1 ring-black ring-opacity-5' : ''"
              @click="setActiveTab('sequence')"
              :tabindex="diagramType === 'sequence' ? '0' : '-1'">
          <span class="p-1.5 lg:pl-2.5 lg:pr-3.5 rounded-md flex items-center text-sm font-medium"
                :class="diagramType === 'sequence' ? 'bg-white shadow-sm ring-1 ring-black ring-opacity-5' : ''">
            <span class="sr-only lg:not-sr-only text-gray-600 group-hover:text-gray-900"
                  :class="diagramType === 'sequence' ? 'text-gray-900' : 'text-gray-600 group-hover:text-gray-900'">Sequence</span>
          </span>
      </button>
      <button type="button"
              class="ml-0.5 p-1.5 lg:pl-2.5 lg:pr-3.5 rounded-md flex items-center text-sm text-gray-600 font-medium focus-visible:ring-2 focus-visible:ring-teal-500 focus-visible:ring-offset-2 focus:outline-none focus-visible:ring-offset-gray-100"
              :class="diagramType === 'mermaid' ? 'bg-white shadow-sm ring-1 ring-black ring-opacity-5' : ''"
              @click="setActiveTab('mermaid')">
        <span class="sr-only lg:not-sr-only text-gray-900"
            :class="diagramType === 'mermaid' ? 'text-gray-900' : 'text-gray-600 group-hover:text-gray-900'">Mermaid</span>
      </button>
    </div>
    <div class="inline-block flex items-center">
      <div class="inline-block ml-2">
        <send-feedback class="ml-2"/>
      </div>
      <a class="inline-block help mx-1 ml-2" target="_blank" :href="helpUrl">
        <button class="flex items-center bg-gray-100 px-2 py-1 text-gray-600 text-sm font-semibold rounded-md" @click="saveAndExit">
          <span>
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
          </span>
          <span>Help</span>
        </button>

      </a>
      <div class="inline-block ml-2">
        <save-and-go-back-button class="ml-2" :saveAndExit="saveAndExit"/>
      </div>
    </div>
  </header>
</template>

<script>
import {mapState} from 'vuex';
import SaveAndGoBackButton from "@/components/SaveAndGoBackButton";
import {DiagramType} from "@/model/Diagram";
import SendFeedback from "@/components/SendFeedback";
import EventBus from "@/EventBus";
export default {
  name: "Header",
  components: {
    SendFeedback,
    SaveAndGoBackButton,
  },
  data() {
    return {
      helpUrl: 'https://zenuml.atlassian.net/wiki/spaces/Doc/overview',
    }
  },
  computed: {
    ...mapState(['code', 'styles', 'mermaidCode', 'diagramType']),
    diagramType() {
      return this.$store.state.diagramType || DiagramType.Sequence
    },
    saveAndExit: function () {
      return function () {
        EventBus.$emit('save')
      }
    }
  },
  methods: {
    setActiveTab(tab) {
      let type = tab === 'sequence' ? DiagramType.Sequence : DiagramType.Mermaid;
      this.$store.dispatch('updateDiagramType', type)
      if (type === DiagramType.Sequence) {
        this.$store.dispatch('reloadZenUML')
      }
    },
  }
}
</script>
