// src/components/SaveAndGoBackButton.vue
<template>
  <div class="save-and-exit inline-block">
    <button class="flex items-center bg-blue-700 p-2 text-white text-sm font-semibold rounded-md" @click="saveAndExit">
      <span>
        <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path></svg>
      </span>
      <span>Save and Go back to Confluence</span>
    </button>
  </div>
</template>

<script>
export default {
  name: "SaveAndGoBackButton",
  props: ['saveAndExit'],
}
</script>

// src/components/react/SaveAndGoBackButton.tsx
import * as React from "react";

interface Props {
  saveAndExit: () => void;
}

export function SaveAndGoBackButton(props: Props) {
  return (
    <div className="save-and-exit inline-block test">
      <button className="flex items-center bg-blue-700 px-2 py-1 text-white text-sm font-semibold rounded" onClick={props.saveAndExit}>
        <span>
          <svg
            className="h-4 w-4"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7"></path>
          </svg>
        </span>
        <span>Save and Go back to Confluence</span>
      </button>
    </div>
  );
}
